### PR TITLE
Fix #148 igbinary_serialize cannot serialize resource(stream)

### LINKED ISSUE #148: igbinary_serialize(): Cannot serialize resource(stream)
Hello

I'm getting this error:

```
A PHP Error was encountered
Severity: 8192

Message: igbinary_serialize(): Cannot serialize resource(stream) and resources may be converted to objects that cannot be serialized in future php releases. Serializing the value as null instead
```

When using v3.4.1 on PHP v8.0.10 (with igbinary v3.2.6) and Guzzle v7.3.0.

This message appears to stem from symfony/cache (v5.3.7) and the memcached component. I'm not getting that message with PHP 7.4 (igbinary 3.1.2) and I think that is because of this change in igbinary:

https://pecl.php.net/package-info.php?package=igbinary&version=3.2.0

> * Emit a deprecation notice when serializing resources.

I have been using the Doctrine cache successfully, but because that is now [deprecated ](https://github.com/doctrine/cache/issues/354) I've been forced to look at alternative implementations.

### PR DESCRIPTION
**Pull request by xavierleune**
When using igbinary_serialize in the process to store a `CacheEntry`, we can get the following warning from PHP: `Message: igbinary_serialize(): Cannot serialize resource(stream) and resources may be converted to objects that cannot be serialized in future php releases. Serializing the value as null instead`. `CacheEntry` already mitigates the fact that a `resource` cannot be serialized, but the `Response` object still contains the `stream` so the warning is still there.

As a workaround, I propose to replace the resource with an instance of `GuzzleHttp\Psr7\PumpStream`, the only implementation of `Psr\Http\Message\StreamInterface` not using a `resource` in its internal, as it's meant to fetch data from a `callback`. In this implementation I've chosen to create a `BodyStore`, with the very minimal logic to return expected data when invoked.

By using this new implementation of `Psr\Http\Message\StreamInterface` for the body, we can totally remove the need to manipulate the `Response` on `__wakeup`

### CODE REVIEW

File: src/CacheEntry.php [hunk 1]
```diff
@@ -265,23 +258,19 @@ public function getAge()
...
         if ($this->response !== null) {
-            $this->responseBody = (string) $this->response->getBody();
-            $this->response->getBody()->rewind();
+            $body = (string)$this->response->getBody();
+            $this->response = $this->response->withBody(
+                new PumpStream(
+                    new BodyStore($body),
+                    [
+                        'size' => mb_strlen($body)
+                    ]
```
Comment (hannesvdvreken) [inline src/CacheEntry.php:269]:
```suggestion
                    [
                        'size' => mb_strlen($body),
                    ]
```

File: src/CacheEntry.php [hunk 2]
```diff
@@ -265,23 +258,19 @@ public function getAge()
...
-    public function __wakeup()
-    {
-        // We re-create the stream of the response
-        if ($this->response !== null) {
-            $this->response = $this->response
-                ->withBody(
-                    \GuzzleHttp\Psr7\Utils::streamFor($this->responseBody)
-                );
-        }
-    }
```
Comment (hannesvdvreken) [inline src/CacheEntry.php:286]: I guess it works without this, but can we do

```
public function __wakeup()
{
    // We re-create the stream of the response
    if ($this->response !== null) {
        $this->response = $this->response
            ->withBody(
                \GuzzleHttp\Psr7\Utils::streamFor((string) $this->response->getBody())
            );
    }
}
```

**Review by hannesvdvreken — APPROVED** [review]
